version: '1.5.3.2-{build}'

image: 
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x86

init:
  - cmd: msbuild /version
 
configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\OpenBVE

build:
  project: C:\projects\OpenBVE\OpenBVE.sln

after_build: 
  - cmd: "\"C:/Program Files (x86)/Inno Setup 5/iss.exe\" /q C:/projects/OpenBVE/installers/windows/openbve.iss"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
